apiVersion: apps/v1
kind: Deployment
metadata:
  name: authsimple
  labels:
    app: authsimple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authsimple
  template:
    metadata:
      labels:
        app: authsimple
    spec:
      containers:
      - name: auth-service-simple
        image: mehike/auth_service_simple:0.0.1
        ports:
        - containerPort: 8086
        env:
        - name: CONFIG_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-host
        - name: CONFIG_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-port
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka-uri
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-user
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Tallinn

